### ISSUE TITLE
Not supported in Android Studio 4.0 ?

### ISSUE THREAD

**Issue by AruLNadhaN** [DVDAndroid/material-color-palette-plugin#6]
I love this plugin. But it is not working now.... While Installing it shows the following error ? 
Plugin 'Material Color Palette' is incompatible with this installation

**Comment by DVDAndroid** [comment]
Hi, can you check if a new 2.0.1 version is available and compatible?

**Comment by DVDAndroid** [comment]
@AruLNadhaN
